version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: notes-db
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: notes-api
    depends_on:
      - postgres

    # ← load ALL your .env vars here (including NOTES_JWT_SECRET etc)
    env_file:
      - .env

    ports:
      - "8080:8080"

volumes:
  pgdata:
