name: Build and Deploy to Raspberry Pi

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/notes-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Copy JAR to Raspberry Pi
        run: |
          scp -o StrictHostKeyChecking=no -P 9999 notes-0.0.1-SNAPSHOT.jar ruslan@77.21.218.107:/home/ruslan/notes-app/app.jar

      - name: Debug Confirm files
        run: |
          ssh -o StrictHostKeyChecking=no -p 9999 ruslan@77.21.218.107 << 'EOF'
            cd notes-app
            git pull origin master
            ls -l Dockerfile
          EOF

      - name: SSH and restart Docker on Pi
        run: |
          ssh -o StrictHostKeyChecking=no -p 9999 ruslan@77.21.218.107 << 'EOF'
            cd notes-app
            docker compose down
            docker compose up -d --build
          EOF
